### ISSUE TITLE
img blurred (heres how to fix it)

### ISSUE THREAD

**Issue by kuronekony4n** [radespratama/pokegames#15]
add this css code to make the all images rendered as pixelated img.

```
img{
    image-rendering: pixelated;
    image-rendering: -moz-crisp-edges;
    image-rendering: crisp-edges;
}
```
Before
![image](https://github.com/radespratama/pokegames/assets/38156932/e1579493-b22d-4a6a-a3a7-42db7e13b767)

After
![image](https://github.com/radespratama/pokegames/assets/38156932/5482cf1a-b1b7-40af-a3aa-6068fb8c2f54)

**Comment by kuronekony4n** [comment]
i'm too lazy for a fork

**Comment by radespratama** [comment]
@kuronekony4n Wow. Thanks dude. Now I'll try to apply it

**Comment by kuronekony4n** [comment]
![image](https://github.com/radespratama/pokegames/assets/38156932/98a48979-07c3-40b7-bf59-856bdbce881d)
some of the images still appear blurred. you forget the animation when catching stuff

**Comment by radespratama** [comment]
Yes, I've already implemented that
